apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-kube-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: argocd-kube
  template:
    metadata:
      labels:
        run: argocd-kube
    spec:
      containers:
      - image: dylee3736/docker-repo:8659378
        name: argocd-kube-container
